# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Serotonin Audio Book
email: hfuecks@gmail.com
description: "An Audio Book Reading Serotonin by Michel Houellebecq"
subtitle: "This is an unauthorized audio book"
lang: en-us
author: Harry Fuecks
copyright: "&#xA9; 2023"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://linkrot.net" # the base hostname & protocol for your site
# twitter_username: timklapdor
# github_username:  timklapdor

permalink: /:year/:title.html

#Timezone
timezone: Europe/Bern

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']